### ISSUE TITLE
Error: There was a problem creating the Core tables. Please report this problem.

### ISSUE THREAD

**Issue by gavin-boyd** [benkeen/generatedata#285]
Get this error at step 3.

**Comment by benkeen** [comment]
Huh, thanks Gavin. You're the second person to report this recently - but the only time I've heard of the problem before. 

Could you tell me a little about the environment you're setting it up on? Server type (flavour of unix, Windows), PHP version, mysql version + browser.

**Comment by blink2004** [comment]
+
OS: Ubuntu 14.10 x64
PHP: 5.4
MySQL: Client API version 5.6.21
Browser: FF 35.0

Screenshot: http://joxi.ru/brRd34KFElPP21

**Comment by blink2004** [comment]
So, problem was been fixed by the next steps
My preview DB name was "dg-online" with symbol "-". It's important. So, I changed name to "dgonline", using only "a-z" characters.
1. Deleted settings.php
2. Reload install.php. First step #1, where retype DB data with new table name
3. Click to next button where was genered data to settings. Seen can't write to settings.php file error message. It's ok.
4. Create settings.php file. Set access by command "chmod 777 settings.php"
5. Click next.
Installation was been success.

So, hope help you.

**Comment by benkeen** [comment]
Thanks @blink2004!
