### ISSUE TITLE
Installation Fails on Step 4

### ISSUE THREAD

**Issue by DougKS** [benkeen/generatedata#300]
During Step 4 of the installation, the installation hangs after generating a few data types (see screen shot). Attempted on all three browsers (IE, Chrome, Firefox). The error reported is a 404 error on the 
<domain>/generatedata-3.2.1/ajax.php 404 (Not Found) file.

The ajax.php was referenced and used earlier, so I'm confused by the error. I am on a hosted environment using:

System: Linux
PHP Version 5.3.28
MySql Version 5.5.42
Apache/2.2.27

Any assistance would be appreciated.

Home4Hosts

![installation-error](https://cloud.githubusercontent.com/assets/1099601/9159026/249fb9d8-3ede-11e5-9ba9-07ab2a7e12a6.png)
)

**Comment by benkeen** [comment]
Hi @DougKS, hmm... puzzling. That URL is correct? `http://careforcehq.com/generatedata/ajax.php`? Your site doesn't require a `www` or anything? 

Could you compare the URL being sent from one of the previous successful requests? I'm curious to know if there's any difference.

Also, what happens when you load that URL into your browser in a separate tab?

**Comment by DougKS** [comment]
The www is optional for most websites. I tried using a fully qualified domain name http://www.careforcehq.com/generatedata-3.2.1/install.php and the installation stalls at the same spot.

**Comment by benkeen** [comment]
Hey @DougKS, kinda stumped here. I know this is asking a lot, but any chance I could be given access to a subfolder on the server (FTP + DB access)? I'd like to try to install it myself + debug it right there. If this is possible, send me an email at ben.keen@gmail.com.

**Comment by DougKS** [comment]
Ben,
I'm not comfortable sharing my main FTP account. I tried creating an FTP
account for you but, it didn't give you access to the folders you probably
need.

I did create a subdomain, with a MySql database and user and a sample
website you can use to attempt a web install. Will that work for now?

Web Install

http://sample.careforcehq.com/generatedata/install.php

Hostname: Localhost
Database: careforc_gendata2
MySql User: careforc_bkeel
MySql P/W : 2rfyfa7gfdw1
Table Prefix: default
Default Language: English

If you can't figure out the issue, how about a WebEx or TeamViewer session?

Thanks for your help,

Doug

**Comment by benkeen** [comment]
Great, thanks Doug - that's terrific! I've taken the info you posted here out the ticket (probably best not to post it online even if it is temporary!)

Just at work right now, but I'll take a look tonight. Hopefully be able to get to the bottom of it pretty quickly. 

Thanks! Keep you posted.

**Comment by benkeen** [comment]
Hi @DougKS, turns out I couldn't get beyond the first screen - it just says `We were unable to connect to the database using the information you supplied. The error message the database returned is: Access denied for user 'careforc_bkee'@'localhost' (using password: YES)`. But now that I think about it, I actually do need the temporary FTP info in order to debug, unfortunately - even with webex or something it would be rather tricky.

Sorry about that. :(

**Comment by benkeen** [comment]
This issue should hopefully be moot with most recent version. Instead of running >50 requests for each plugin, now it just runs three, one for each type. I believe it'll get around this issue.

**Comment by benkeen** [comment]
Closing. Please re-open if there are still problems.
