### ISSUE TITLE
Boolean

### ISSUE THREAD

**Issue by EmilMoe** [benkeen/generatedata#303]
Very nice tool!

But I can't find a way to randomize a true|false option column?

**Comment by benkeen** [comment]
Thanks! Try the `Custom List` Data Type. Just enter `true|false` in the options and I think that'll do it...!

**Comment by emilmoe** [comment]
That's an option, but it adds " around it like "true" and "false". In JSON for example boolean values are a type and therefore without. It's not critical as I only use it for demo, but I think you should add boolean under math.

**Comment by benkeen** [comment]
Ahh good call. I agree.

**Comment by emilmoe** [comment]
I wanted to fork it to you, but you have a design mistake in your JSON output or in general in your output.

I think you should let the plugin allow to cast a return to whatever it wants and let it up to the plugin to handle it. At least list all simple possible casts in PHP (boolean, string, integer, float, etc.) Right now it's not easy to add this feature to your script because the main script doesn't allow plugins to return booleans.

**Comment by benkeen** [comment]
Hmm. No, not a design flaw. I knew I’d never be able to make it generic enough to handle every imaginable scenario that people dream up for data generation, so there’s an optional “generationOptions” key that can be returned by any data type’s generate() method. See:
http://benkeen.github.io/generatedata/dataTypes.html#phpClassMethods

That can be used to pass arbitrary info from a Data Type to an Export Type, e.g. “boolean” => true. The Export Type would need to be updated to look for that value and know not to output double quotes in that scenario. Be nice to make it generic enough to work for other scenarios too, so maybe a “noDecoration” => true or something.

**Comment by emilmoe** [comment]
I will try to implement that and change my pull request.

**Comment by benkeen** [comment]
Hi @EmilMoe, just FYI, this was added by Conrad Hagemans and merged a while back:
https://github.com/benkeen/generatedata/tree/master/plugins/dataTypes/Boolean

It'll be included in the next release.
