### ISSUE TITLE
** MAJOR ** Cannot import to CSV

### ISSUE THREAD

**Issue by soke1556** [benkeen/generatedata#384]
The option is not even available.

**Comment by soke1556** [comment]
Further info: I can't see the CSV tab when I'm logged in (Which I need since I need to export more than 100 rows).

**Comment by benkeen** [comment]
Hmm, curious! I refunded your account, but I'm rather interested in getting to the bottom of this.

When you go to the Settings tab, do you have the CSV export type checked? That tab governs what you see in the UI, so that would be my first guess. But you'd have had to have disabled it at one point.
